/** \file libvot_config.h
 *	\brief Configurations file generated by CMake
 */
// the configured options and settings for libvot
#define LIBVOT_VERSION_MAJOR 0
#define LIBVOT_VERSION_MINOR 1
#define LIBVOT_VERSION_PATCH 3
